//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenomNetGuard.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VenomNetGuard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Activity detected: {0}
        ///IP: {1}
        ///[Silenced for 8s].
        /// </summary>
        public static string BalloonAlertMsg {
            get {
                return ResourceManager.GetString("BalloonAlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný VENOM ALERT: {0}.
        /// </summary>
        public static string BalloonAlertTitle {
            get {
                return ResourceManager.GetString("BalloonAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sensor successfully activated and listening in the background..
        /// </summary>
        public static string BalloonMsgActivated {
            get {
                return ResourceManager.GetString("BalloonMsgActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Venom NetGuard is still running in the background. Right-click the tray icon to exit completely..
        /// </summary>
        public static string BalloonMsgMinimized {
            get {
                return ResourceManager.GetString("BalloonMsgMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný VENOM NETGUARD.
        /// </summary>
        public static string BalloonTitleCore {
            get {
                return ResourceManager.GetString("BalloonTitleCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný [►] EVENT LOG SCANNER.
        /// </summary>
        public static string BtnEventLogScanner {
            get {
                return ResourceManager.GetString("BtnEventLogScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný MARK ALL AS REVIEWED.
        /// </summary>
        public static string BtnMarkReviewed {
            get {
                return ResourceManager.GetString("BtnMarkReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný [ ] PACKET SNIFFER (LOCKED).
        /// </summary>
        public static string BtnPacketSniffer {
            get {
                return ResourceManager.GetString("BtnPacketSniffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný REVIEW.
        /// </summary>
        public static string BtnReview {
            get {
                return ResourceManager.GetString("BtnReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný [⚙] SETTINGS.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ENABLE TRAY ALERTS.
        /// </summary>
        public static string ChkEnableTrayAlerts {
            get {
                return ResourceManager.GetString("ChkEnableTrayAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CRITICAL.
        /// </summary>
        public static string ChkFilterCritical {
            get {
                return ResourceManager.GetString("ChkFilterCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný INFO.
        /// </summary>
        public static string ChkFilterInfo {
            get {
                return ResourceManager.GetString("ChkFilterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný WARNING.
        /// </summary>
        public static string ChkFilterWarning {
            get {
                return ResourceManager.GetString("ChkFilterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NOTIFY CRITICAL (5140).
        /// </summary>
        public static string ChkNotifyCritical {
            get {
                return ResourceManager.GetString("ChkNotifyCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný NOTIFY WARNINGS (4625).
        /// </summary>
        public static string ChkNotifyWarnings {
            get {
                return ResourceManager.GetString("ChkNotifyWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RUN VENOM NETGUARD AT SYSTEM STARTUP (STEALTH).
        /// </summary>
        public static string ChkRunAtStartup {
            get {
                return ResourceManager.GetString("ChkRunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Terminate Venom NetGuard.
        /// </summary>
        public static string CtxTerminateNexus {
            get {
                return ResourceManager.GetString("CtxTerminateNexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný EVENT TARGET (SHARE/PORT).
        /// </summary>
        public static string DgColEventTarget {
            get {
                return ResourceManager.GetString("DgColEventTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SEV.
        /// </summary>
        public static string DgColSev {
            get {
                return ResourceManager.GetString("DgColSev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SOURCE IP.
        /// </summary>
        public static string DgColSourceIp {
            get {
                return ResourceManager.GetString("DgColSourceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TIMESTAMP.
        /// </summary>
        public static string DgColTimestamp {
            get {
                return ResourceManager.GetString("DgColTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Venom NetGuard initialized. Listening to Windows Security Events....
        /// </summary>
        public static string LogNexusInitialized {
            get {
                return ResourceManager.GetString("LogNexusInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed Logon (Event 4625).
        /// </summary>
        public static string LogTargetFailedLogon {
            get {
                return ResourceManager.GetString("LogTargetFailedLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Security Log Cleared (Event 1102).
        /// </summary>
        public static string LogTargetLogCleared {
            get {
                return ResourceManager.GetString("LogTargetLogCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Network Share Accessed (Event 5140).
        /// </summary>
        public static string LogTargetShareAccessed {
            get {
                return ResourceManager.GetString("LogTargetShareAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New User Account Created (Event 4720).
        /// </summary>
        public static string LogTargetUserCreated {
            get {
                return ResourceManager.GetString("LogTargetUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný System blocked access to logs.
        ///Reason: {0}
        ///
        ///Make sure you run Visual Studio (or the App) as Administrator!.
        /// </summary>
        public static string MsgBoxAccessDeniedMsg {
            get {
                return ResourceManager.GetString("MsgBoxAccessDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný VENOM NETGUARD: Access Denied.
        /// </summary>
        public static string MsgBoxAccessDeniedTitle {
            get {
                return ResourceManager.GetString("MsgBoxAccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Venom NetGuard Monitoring.
        /// </summary>
        public static string TrayIconText {
            get {
                return ResourceManager.GetString("TrayIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ALERT SETTINGS.
        /// </summary>
        public static string TxtAlertSettings {
            get {
                return ResourceManager.GetString("TxtAlertSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FILTER BY:.
        /// </summary>
        public static string TxtFilterBy {
            get {
                return ResourceManager.GetString("TxtFilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný VENOM // NETGUARD.
        /// </summary>
        public static string TxtNexusCore {
            get {
                return ResourceManager.GetString("TxtNexusCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PENDING REVIEW.
        /// </summary>
        public static string TxtPendingReview {
            get {
                return ResourceManager.GetString("TxtPendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SECURE.
        /// </summary>
        public static string TxtSecure {
            get {
                return ResourceManager.GetString("TxtSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SYSTEM PREFERENCES.
        /// </summary>
        public static string TxtSettingsTitle {
            get {
                return ResourceManager.GetString("TxtSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registers a high-privilege scheduled task to run silently on the background without UAC prompts..
        /// </summary>
        public static string TxtStartupDesc {
            get {
                return ResourceManager.GetString("TxtStartupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SYSTEM STATUS.
        /// </summary>
        public static string TxtSystemStatus {
            get {
                return ResourceManager.GetString("TxtSystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný WARNINGS (24h).
        /// </summary>
        public static string TxtWarnings24h {
            get {
                return ResourceManager.GetString("TxtWarnings24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unknown IP / Local.
        /// </summary>
        public static string UnknownIp {
            get {
                return ResourceManager.GetString("UnknownIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Venom NetGuard - Tactical Dashboard.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
